// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDaC-AXKLSIO50W6bfjTNINcytDB4dmtMY",
    appId: "1:469913225378:android:4caa7fa9b4e0590b082ffb",
    databaseURL: "https://phasamue-b51ba-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: "469913225378",
    projectId: "phasamue-b51ba",
    authDomain: 'live-stream-31a10.firebaseapp.com',
    storageBucket: 'live-stream-31a10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDaC-AXKLSIO50W6bfjTNINcytDB4dmtMY",
    appId: "1:469913225378:android:4caa7fa9b4e0590b082ffb",
    databaseURL: "https://phasamue-b51ba-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: "469913225378",
    projectId: "phasamue-b51ba",
    storageBucket: 'live-stream-31a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDaC-AXKLSIO50W6bfjTNINcytDB4dmtMY",
    appId: "1:469913225378:android:4caa7fa9b4e0590b082ffb",
    databaseURL: "https://phasamue-b51ba-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: "469913225378",
    projectId: "phasamue-b51ba",
    storageBucket: 'live-stream-31a10.appspot.com',
    iosClientId: '7086588376-aobp8cvaer1lj4jj9j07slug5kn35f9b.apps.googleusercontent.com',
    iosBundleId: 'io.flutterflow.flutterMuxLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQH05iso_zVqs95wMQ5BoSBby0u5x6rE',
    appId: '1:7086588376:ios:e2c1a205109927e657b2ad',
    messagingSenderId: '7086588376',
    projectId: 'live-stream-31a10',
    storageBucket: 'live-stream-31a10.appspot.com',
    iosClientId: '7086588376-aobp8cvaer1lj4jj9j07slug5kn35f9b.apps.googleusercontent.com',
    iosBundleId: 'io.flutterflow.flutterMuxLive',
  );
}